### PR TITLE
Many updates

### PR DESCRIPTION
**Pull request by stardiviner**
Seems this repo is not maintained for a very long time.
I might consider push my fork for MELPA.

### CODE REVIEW

**Comment by casouri** [comment]
I should have a look at PR's earlier! @stardiviner How is your upload/compile implemented? Are you using [this](https://github.com/arduino/arduino-cli)? Thanks.

**Comment by stardiviner** [comment]
@casouri No, I use Arduino command-line tool `arduino` with option `--upload [file]`. Also verify use this command too. You can check it out here: https://github.com/stardiviner/arduino-mode/blob/master/arduino-mode.el#L218

**Comment by stardiviner** [comment]
Also, I have already take over the `arduino-mode` project. I'm maintaining it. I also merged some PRs from others.

**Comment by casouri** [comment]
Cool, sadly my code is unnecessary since you have already implemented those features. Is there any way to replace this repo with yours when people search in google? I could have saved a lot of time if I saw your fork earlier.

**Comment by stardiviner** [comment]
@casouri Actually currently MELPA recipe already using my fork. And I also contacted bookest about taking over the maintainship. If you install arduino-mode from Emacs ELPA repo. You should already have it. As for google searching result ranking, I think there are two solution, this repo add a README to link to my fork. Or add the fork's popularity. Actually I was guess bookest might still will add code on it in future. And my fork don't have much feature to add now. Because I'm not playing around Arduino recently neither. But I will maintain it, PR welcome.

**Comment by apiraino** [comment]
@stardiviner could you manage to push your fork to Melpa?

that would be great :)

**Comment by stardiviner** [comment]
Actually, current MELPA version already point to my repo long time ago. I got maintainer's agreement and updated MELPA recipe.

**Comment by apiraino** [comment]
ah thank you. For reference, the relevant PR [is this](https://github.com/melpa/melpa/pull/5290).

**Pull request closed without merging**
